apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - port: {{ .Values.usersService.port }}
      targetPort: {{ .Values.usersService.port }}
